### ISSUE TITLE
Ultramarathon distances missing

### ISSUE THREAD

**Issue by atoponce** [Tyler-Lopez/StravaActivitiesVisualizer#26]
[Per our Reddit discussion](https://www.reddit.com/r/Strava/comments/10nqrtq/i_built_an_android_app_to_make_customizable/j8pz1ox/?context=10000), creating an issue here for you to track. There are two ultramarathon runs of mine, one labeled as a standard "Run" activity, and the other a "Trail Run", both races, that are missing without filters being applied to exclude them.

The two runs are:

- https://www.strava.com/activities/7282015676
- https://www.strava.com/activities/7518011437

**Comment by Tyler-Lopez** [comment]
Thanks for opening this!

It's unlikely to be correlated with the long distance as another athlete was loaded a 50-mile run without issue. I'm curious about other possible culprits too. For example, if all runs by that recording device (Suunto Ambit3 Peak) are missing.

It would be helpful to know if they were also missing from a comparable service, like this: 
https://customization.mapridesshop.com/ 

If they are, it might be that the API method to get all activities is struggling with these two runs. https://developers.strava.com/docs/reference/#api-Activities-getLoggedInAthleteActivities 

Unfortunately, this application doesn't yet have the analytics for me to debug the API response you are receiving.

Regardless, I'll plan to make a new section on the home screen under settings where an Activity ID may be input directly - that would use a different API method https://developers.strava.com/docs/reference/#api-Activities-getActivityById

**Comment by atoponce** [comment]
> I'm curious about other possible culprits too. For example, if all runs by that recording device (Suunto Ambit3 Peak) are missing.

Actually, that might be it. When the app loads, it only finds 553 total activities, although according to Strava, I've recorded 1,176, most with GPS tracks. I have 576 runs (all public) and 527 walks (most private).

All my runs in 2021 are recorded with the Suunto Ambit3 Peak watch, and if I filter by 2021, some show up, but *very few of them*—only 35 in total. I averaged 4 runs per week Jan-Sep 2021 and 5 runs per week Oct-Dec 2021, most of them overwhelmingly outside with GPS tracks. That should be around 200+ runs. So I'm missing roughly 85% of my 2021 runs.

If I filter by 2022, the total distance reported is 1,284 miles, even though I know I ran 2,800 miles (it was a goal to hit 3,000, but health got in the way), most with GPS tracks. However, it also shows track workouts early in the art. The first track workout is the 10th track on the top row, although I didn't execute that workout until August 2022, which would be a over 150 runs later. I executed that workout with and most of the runs following my new Suunto 9 Baro.

If I filter by 2023, 43 activities are loaded, and they all seem to be Suunto 9 Baro recorded and they all seem to be present. The ones I did record with my Ambit3 Peak do seem to be missing.

So yeah, it does seem reasonable at least that the Suunto Ambit3 Peak activities aren't getting loaded. You might be on to something there. Perhaps the Ambit3 Peak is doing something unexpected to the GPX data?

**Comment by atoponce** [comment]
> It would be helpful to know if they were also missing from a comparable service, like this:
https://customization.mapridesshop.com/

This service appears to be grabbing every activity, including the original ultramarathon distances mentioned.

**Comment by Tyler-Lopez** [comment]
> > It would be helpful to know if they were also missing from a comparable service, like this:
> > https://customization.mapridesshop.com/
> 
> This service appears to be grabbing every activity, including the original ultramarathon distances mentioned.

Good to know! My wild guess based on that information (without being able to see your API response within Activity Art) is that this other service may not provide the `before` and `after` properties when they make [the query](https://developers.strava.com/docs/reference/#api-Activities-getLoggedInAthleteActivities). This would instead return all activities.

Perhaps behind the scenes at Strava, these activities have some issue with their epoch timestamp, filtering them when my query includes `before` and `after` but which does not cause a problem when those parameters are omitted. I'll keep exploring this to test the hypothesis and add more debugging tools.

**Comment by Tyler-Lopez** [comment]
@atoponce 

Hi, I just released an update that removes these `before` and `after` properties I mentioned.

That other service is sort of open-source via. Inspect and they, as I was thinking, do not use `before` and `after`.

![image](https://user-images.githubusercontent.com/77797048/219838144-bbf7ea2c-8641-4caf-8711-6d43912a0665.png)

If you get a chance, please let me know if this fixes it! :)

**Comment by atoponce** [comment]
That seemed to have worked. I now have 1,052 activities loaded which is more on par with what I would expect. I see the ultramarathons this issue was initially about, and the 2023 activities all seem to be inline with what I would expect so far for this year.

Thanks for addressing this! From my perspective, this is fixed. I'll close the issue.
